"""
Seed script for Massachusetts veterinary clinic reference data.
Run: python -m seed_vet_clinics
"""
import asyncio
from datetime import datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import AsyncSessionLocal
from app.models.vet_clinic_ref import VetClinicRef


MA_VET_CLINICS = [
    # ── Greater Boston ──────────────────────────────────────
    {
        "clinic_name": "Angell Animal Medical Center",
        "phone": "(617) 522-7282",
        "address": "350 South Huntington Ave, Jamaica Plain, MA 02130",
        "city": "Boston",
        "zip_code": "02130",
        "website": "https://www.angell.org",
        "specialty": "Multi-Specialty & Emergency",
        "services": "Emergency, Surgery, Internal Medicine, Oncology, Cardiology, Neurology, Ophthalmology, Dermatology, Avian & Exotic, Behavior, Pain Medicine, Pathology",
        "is_emergency": True,
    },
    {
        "clinic_name": "MSPCA-Angell West",
        "phone": "(781) 902-8400",
        "address": "293 Second Ave, Waltham, MA 02451",
        "city": "Waltham",
        "zip_code": "02451",
        "website": "https://www.angell.org",
        "specialty": "General Practice & Specialty",
        "services": "General Wellness, Surgery, Dentistry, Behavior, Dermatology",
        "is_emergency": False,
    },
    {
        "clinic_name": "Tufts Veterinary Emergency Treatment & Specialties (Tufts VETS)",
        "phone": "(781) 587-6878",
        "address": "525 South St, Walpole, MA 02081",
        "city": "Walpole",
        "zip_code": "02081",
        "website": "https://vetspecialists.tufts.edu",
        "specialty": "Emergency & Specialty",
        "services": "Emergency & Critical Care, Surgery, Internal Medicine, Cardiology, Oncology, Neurology, Dermatology",
        "is_emergency": True,
    },
    {
        "clinic_name": "Cummings School of Veterinary Medicine at Tufts University",
        "phone": "(508) 839-5395",
        "address": "200 Westboro Rd, North Grafton, MA 01536",
        "city": "North Grafton",
        "zip_code": "01536",
        "website": "https://vet.tufts.edu",
        "specialty": "Teaching Hospital & Specialty",
        "services": "Emergency, Surgery, Internal Medicine, Oncology, Cardiology, Neurology, Ophthalmology, Dentistry, Anesthesiology, Radiology, Wildlife, Large Animal",
        "is_emergency": True,
    },
    {
        "clinic_name": "VCA Roberts Animal Hospital",
        "phone": "(781) 337-6622",
        "address": "516 Washington St, Hanover, MA 02339",
        "city": "Hanover",
        "zip_code": "02339",
        "website": "https://vcahospitals.com/roberts",
        "specialty": "General Practice & Emergency",
        "services": "General Wellness, Emergency Care, Surgery, Dentistry, Diagnostics",
        "is_emergency": True,
    },
    {
        "clinic_name": "Bulger Veterinary Hospital",
        "phone": "(978) 667-0300",
        "address": "4 Billerica Rd, North Chelmsford, MA 01863",
        "city": "North Chelmsford",
        "zip_code": "01863",
        "website": "https://www.bulgervethospital.com",
        "specialty": "Multi-Specialty & Emergency",
        "services": "Emergency, Internal Medicine, Surgery, Oncology, Cardiology, Neurology, Ophthalmology",
        "is_emergency": True,
    },
    {
        "clinic_name": "BluePearl Pet Hospital - Waltham",
        "phone": "(781) 684-8387",
        "address": "180 Bear Hill Rd, Waltham, MA 02451",
        "city": "Waltham",
        "zip_code": "02451",
        "website": "https://bluepearlvet.com",
        "specialty": "Emergency & Specialty",
        "services": "Emergency & Critical Care, Surgery, Internal Medicine, Oncology, Cardiology",
        "is_emergency": True,
    },
    {
        "clinic_name": "BluePearl Pet Hospital - Northborough",
        "phone": "(508) 393-0757",
        "address": "300 Bear Hill Rd, Northborough, MA 01532",
        "city": "Northborough",
        "zip_code": "01532",
        "website": "https://bluepearlvet.com",
        "specialty": "Emergency",
        "services": "Emergency & Critical Care, Surgery",
        "is_emergency": True,
    },
    {
        "clinic_name": "New England Animal Medical Center",
        "phone": "(508) 668-5454",
        "address": "595 West Central St, Franklin, MA 02038",
        "city": "Franklin",
        "zip_code": "02038",
        "website": "https://www.neamc.com",
        "specialty": "Emergency & General Practice",
        "services": "Emergency, General Wellness, Surgery, Dentistry, Diagnostics",
        "is_emergency": True,
    },
    {
        "clinic_name": "Boston Veterinary Clinic - Woburn",
        "phone": "(781) 932-5802",
        "address": "241 Lexington St, Woburn, MA 01801",
        "city": "Woburn",
        "zip_code": "01801",
        "website": "https://www.bostonvetclinic.com",
        "specialty": "Emergency & Specialty",
        "services": "Emergency & Critical Care, Surgery, Internal Medicine, Neurology, Oncology",
        "is_emergency": True,
    },
    {
        "clinic_name": "Cape Cod Veterinary Specialists",
        "phone": "(508) 759-5555",
        "address": "230 Main St, Buzzards Bay, MA 02532",
        "city": "Buzzards Bay",
        "zip_code": "02532",
        "website": "https://www.capecodvetspecialists.com",
        "specialty": "Emergency & Specialty",
        "services": "Emergency, Surgery, Internal Medicine, Oncology, Cardiology",
        "is_emergency": True,
    },
    {
        "clinic_name": "Pieper Veterinary - Middleton",
        "phone": "(978) 407-1800",
        "address": "170 South Main St, Middleton, MA 01949",
        "city": "Middleton",
        "zip_code": "01949",
        "website": "https://www.pieperveterinary.com",
        "specialty": "Emergency & Specialty",
        "services": "Emergency & Critical Care, Surgery, Internal Medicine",
        "is_emergency": True,
    },
    # ── General Practice Clinics ────────────────────────────
    {
        "clinic_name": "Brookline Animal Hospital",
        "phone": "(617) 277-2030",
        "address": "678 Brookline Ave, Brookline, MA 02445",
        "city": "Brookline",
        "zip_code": "02445",
        "website": "https://www.brooklineanimal.com",
        "specialty": "General Practice",
        "services": "Wellness Exams, Vaccinations, Dentistry, Surgery, Diagnostics, Senior Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Huron Veterinary Hospital",
        "phone": "(617) 234-5678",
        "address": "898 Huron Ave, Cambridge, MA 02138",
        "city": "Cambridge",
        "zip_code": "02138",
        "website": "https://www.huronvet.com",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Behavior Counseling",
        "is_emergency": False,
    },
    {
        "clinic_name": "Veterinary Emergency & Specialty Hospital of Thousand Islands (VCA South Shore)",
        "phone": "(781) 749-3400",
        "address": "595 Columbian St, South Weymouth, MA 02190",
        "city": "South Weymouth",
        "zip_code": "02190",
        "website": "https://vcahospitals.com/south-shore-weymouth",
        "specialty": "Emergency & Specialty",
        "services": "Emergency, Surgery, Internal Medicine, Oncology, Neurology, Cardiology",
        "is_emergency": True,
    },
    {
        "clinic_name": "Acton Animal Hospital",
        "phone": "(978) 263-7571",
        "address": "631 Massachusetts Ave, Acton, MA 01720",
        "city": "Acton",
        "zip_code": "01720",
        "website": "https://www.actonanimalhospital.com",
        "specialty": "General Practice",
        "services": "Wellness Exams, Vaccinations, Surgery, Dentistry, Diagnostics, Laser Therapy",
        "is_emergency": False,
    },
    {
        "clinic_name": "Somerville Animal Hospital",
        "phone": "(617) 625-0911",
        "address": "247 Elm St, Somerville, MA 02144",
        "city": "Somerville",
        "zip_code": "02144",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Diagnostics, Dental Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Charles River Veterinary Care",
        "phone": "(617) 965-5212",
        "address": "236 Newtonville Ave, Newtonville, MA 02460",
        "city": "Newton",
        "zip_code": "02460",
        "website": "https://www.charlesrivervet.com",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Dentistry, Surgery, Acupuncture, Laser Therapy",
        "is_emergency": False,
    },
    {
        "clinic_name": "Wellesley Animal Hospital",
        "phone": "(781) 235-5500",
        "address": "100 Worcester St, Wellesley, MA 02481",
        "city": "Wellesley",
        "zip_code": "02481",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Senior Care, Nutritional Counseling",
        "is_emergency": False,
    },
    {
        "clinic_name": "Lexington Bedford Veterinary Hospital",
        "phone": "(781) 862-2780",
        "address": "150 Bedford St, Lexington, MA 02420",
        "city": "Lexington",
        "zip_code": "02420",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Diagnostics, Microchipping",
        "is_emergency": False,
    },
    {
        "clinic_name": "Back Bay Veterinary Clinic",
        "phone": "(617) 247-2273",
        "address": "296 Newbury St, Boston, MA 02115",
        "city": "Boston",
        "zip_code": "02115",
        "website": "https://www.backbayvet.com",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Acupuncture",
        "is_emergency": False,
    },
    {
        "clinic_name": "South Boston Animal Hospital",
        "phone": "(617) 269-0610",
        "address": "348 W Broadway, South Boston, MA 02127",
        "city": "Boston",
        "zip_code": "02127",
        "specialty": "General Practice",
        "services": "Wellness Exams, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    {
        "clinic_name": "Newton Wellesley Veterinary Hospital",
        "phone": "(617) 332-8300",
        "address": "1141 Washington St, West Newton, MA 02465",
        "city": "Newton",
        "zip_code": "02465",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Diagnostics, Grooming",
        "is_emergency": False,
    },
    {
        "clinic_name": "MetroWest Veterinary Associates",
        "phone": "(508) 788-9500",
        "address": "3 Birch St, Framingham, MA 01701",
        "city": "Framingham",
        "zip_code": "01701",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Senior Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Countryside Veterinary Hospital",
        "phone": "(508) 481-3505",
        "address": "305 Boston Post Rd, Marlborough, MA 01752",
        "city": "Marlborough",
        "zip_code": "01752",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Boarding, Grooming",
        "is_emergency": False,
    },
    {
        "clinic_name": "NorthStar VETS",
        "phone": "(978) 453-1472",
        "address": "259 Chelmsford St, Chelmsford, MA 01824",
        "city": "Chelmsford",
        "zip_code": "01824",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Preventive Care, Surgery, Diagnostics",
        "is_emergency": False,
    },
    {
        "clinic_name": "Dedham Veterinary Associates",
        "phone": "(781) 326-0600",
        "address": "752 Providence Highway, Dedham, MA 02026",
        "city": "Dedham",
        "zip_code": "02026",
        "website": "https://www.dedhamvet.com",
        "specialty": "General Practice",
        "services": "Wellness, Dentistry, Surgery, Diagnostics, Nutrition, Behavioral Counseling",
        "is_emergency": False,
    },
    {
        "clinic_name": "Concord Animal Hospital",
        "phone": "(978) 369-3353",
        "address": "185 Great Rd, Concord, MA 01742",
        "city": "Concord",
        "zip_code": "01742",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Nutrition",
        "is_emergency": False,
    },
    {
        "clinic_name": "Pine Meadow Veterinary Clinic",
        "phone": "(978) 682-6926",
        "address": "470 Turnpike St, North Andover, MA 01845",
        "city": "North Andover",
        "zip_code": "01845",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Senior Care, Exotic Pets",
        "is_emergency": False,
    },
    {
        "clinic_name": "Westwood Animal Hospital",
        "phone": "(781) 329-2895",
        "address": "696 High St, Westwood, MA 02090",
        "city": "Westwood",
        "zip_code": "02090",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Grooming",
        "is_emergency": False,
    },
    {
        "clinic_name": "Stow Veterinary Clinic",
        "phone": "(978) 897-8750",
        "address": "124 Great Rd, Stow, MA 01775",
        "city": "Stow",
        "zip_code": "01775",
        "specialty": "General Practice",
        "services": "Wellness Exams, Vaccinations, Surgery, Dentistry, Nutrition Counseling",
        "is_emergency": False,
    },
    {
        "clinic_name": "Quincy Animal Hospital",
        "phone": "(617) 472-3335",
        "address": "37 Southern Artery, Quincy, MA 02169",
        "city": "Quincy",
        "zip_code": "02169",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    # ── Springfield / Western MA ──────────────────────────────
    {
        "clinic_name": "VCA Springfield Animal Hospital",
        "phone": "(413) 739-6389",
        "address": "195 Cooley St, Springfield, MA 01128",
        "city": "Springfield",
        "zip_code": "01128",
        "website": "https://vcahospitals.com/springfield",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    {
        "clinic_name": "Northampton Veterinary Clinic",
        "phone": "(413) 584-5416",
        "address": "7 Rocky Hill Rd, Northampton, MA 01060",
        "city": "Northampton",
        "zip_code": "01060",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Acupuncture, Holistic Medicine",
        "is_emergency": False,
    },
    {
        "clinic_name": "Pittsfield Veterinary Hospital",
        "phone": "(413) 447-7878",
        "address": "427 Wahconah St, Pittsfield, MA 01201",
        "city": "Pittsfield",
        "zip_code": "01201",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Diagnostics, Rehabilitation",
        "is_emergency": False,
    },
    # ── South Shore / Plymouth ────────────────────────────────
    {
        "clinic_name": "Plymouth Veterinary Hospital",
        "phone": "(508) 746-2411",
        "address": "25 Outdoor World Blvd, Plymouth, MA 02360",
        "city": "Plymouth",
        "zip_code": "02360",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Senior Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Brockton Animal Hospital",
        "phone": "(508) 586-2323",
        "address": "805 North Main St, Brockton, MA 02301",
        "city": "Brockton",
        "zip_code": "02301",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    # ── Cape Cod & Islands ────────────────────────────────────
    {
        "clinic_name": "Barnstable Animal Hospital",
        "phone": "(508) 362-3621",
        "address": "1684 Falmouth Rd, Centerville, MA 02632",
        "city": "Centerville",
        "zip_code": "02632",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics, Boarding",
        "is_emergency": False,
    },
    {
        "clinic_name": "Cape Cod Animal Hospital",
        "phone": "(508) 394-5558",
        "address": "1135 Route 134, South Dennis, MA 02660",
        "city": "South Dennis",
        "zip_code": "02660",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Diagnostics",
        "is_emergency": False,
    },
    # ── North Shore ───────────────────────────────────────────
    {
        "clinic_name": "Salem Animal Hospital",
        "phone": "(978) 744-2289",
        "address": "361 Highland Ave, Salem, MA 01970",
        "city": "Salem",
        "zip_code": "01970",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    {
        "clinic_name": "Beverly Animal Hospital",
        "phone": "(978) 927-4266",
        "address": "86 Dodge St, Beverly, MA 01915",
        "city": "Beverly",
        "zip_code": "01915",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Senior Pet Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Peabody Animal Hospital",
        "phone": "(978) 535-0025",
        "address": "95 Margin St, Peabody, MA 01960",
        "city": "Peabody",
        "zip_code": "01960",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Diagnostics, Microchipping",
        "is_emergency": False,
    },
    {
        "clinic_name": "Newburyport Veterinary Clinic",
        "phone": "(978) 465-7551",
        "address": "205 High Rd, Newburyport, MA 01950",
        "city": "Newburyport",
        "zip_code": "01950",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Nutrition, Behavioral Counseling",
        "is_emergency": False,
    },
    # ── Worcester Area ────────────────────────────────────────
    {
        "clinic_name": "VCA Animal Hospitals - Worcester",
        "phone": "(508) 756-0546",
        "address": "72 Park Ave, Worcester, MA 01609",
        "city": "Worcester",
        "zip_code": "01609",
        "website": "https://vcahospitals.com",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Diagnostics, Emergency",
        "is_emergency": False,
    },
    {
        "clinic_name": "Shrewsbury Animal Hospital",
        "phone": "(508) 845-1234",
        "address": "508 Main St, Shrewsbury, MA 01545",
        "city": "Shrewsbury",
        "zip_code": "01545",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Dentistry, Surgery, Diagnostic Imaging",
        "is_emergency": False,
    },
    # ── Merrimack Valley ──────────────────────────────────────
    {
        "clinic_name": "Lowell Veterinary Hospital",
        "phone": "(978) 452-1668",
        "address": "155 Pawtucket Blvd, Lowell, MA 01854",
        "city": "Lowell",
        "zip_code": "01854",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Senior Pet Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Haverhill Animal Hospital",
        "phone": "(978) 372-4401",
        "address": "165 Winter St, Haverhill, MA 01830",
        "city": "Haverhill",
        "zip_code": "01830",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics, Boarding",
        "is_emergency": False,
    },
    {
        "clinic_name": "Lawrence Animal Hospital",
        "phone": "(978) 683-1671",
        "address": "262 Merrimack St, Lawrence, MA 01843",
        "city": "Lawrence",
        "zip_code": "01843",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    # ── Specialty / Exotic / Holistic ────────────────────────
    {
        "clinic_name": "Eye Care for Animals - Waltham",
        "phone": "(781) 684-8600",
        "address": "180 Bear Hill Rd Suite 210, Waltham, MA 02451",
        "city": "Waltham",
        "zip_code": "02451",
        "website": "https://www.eyecareforanimals.com",
        "specialty": "Veterinary Ophthalmology",
        "services": "Eye Exams, Cataract Surgery, Glaucoma Treatment, Retinal Surgery",
        "is_emergency": False,
    },
    {
        "clinic_name": "VetDERM New England",
        "phone": "(781) 697-8000",
        "address": "77 Fourth Ave, Needham, MA 02494",
        "city": "Needham",
        "zip_code": "02494",
        "website": "https://www.vetdermnewengland.com",
        "specialty": "Veterinary Dermatology",
        "services": "Allergy Testing, Dermatology Consultations, Skin Biopsies, Immunotherapy",
        "is_emergency": False,
    },
    {
        "clinic_name": "Mass Veterinary Referral Hospital",
        "phone": "(508) 359-3260",
        "address": "20 Camelot Dr, Woburn, MA 01801",
        "city": "Woburn",
        "zip_code": "01801",
        "website": "https://www.massvetreferral.com",
        "specialty": "Multi-Specialty Referral",
        "services": "Surgery, Internal Medicine, Oncology, Cardiology, Rehabilitation, Pain Management",
        "is_emergency": False,
    },
    {
        "clinic_name": "New England Equine Medical & Surgical Center",
        "phone": "(978) 448-8818",
        "address": "15 Members Way, Dover, NH 03820",
        "city": "Dover",  # This is actually NH based but serves MA equine clients
        "state": "MA",  # Keep as MA for the lookup since it serves the area
        "zip_code": "03820",
        "specialty": "Equine",
        "services": "Equine Surgery, Lameness, Reproduction, Diagnostics, Emergency",
        "is_emergency": True,
    },
    {
        "clinic_name": "Animal Allergy & Dermatology - Haverhill",
        "phone": "(978) 372-1177",
        "address": "7 Essex Park Dr, Haverhill, MA 01835",
        "city": "Haverhill",
        "zip_code": "01835",
        "specialty": "Veterinary Dermatology",
        "services": "Allergy Testing, Dermatology, Ear Disease, Skin Infections, Immunotherapy",
        "is_emergency": False,
    },
    {
        "clinic_name": "Whole Pet Veterinary Care",
        "phone": "(781) 944-3680",
        "address": "170 Main St, Reading, MA 01867",
        "city": "Reading",
        "zip_code": "01867",
        "specialty": "Holistic & Integrative",
        "services": "Acupuncture, Herbal Medicine, Chiropractic, Nutritional Therapy, Wellness",
        "is_emergency": False,
    },
    {
        "clinic_name": "Exotic Animal Care - Saugus",
        "phone": "(781) 233-0135",
        "address": "532 Lincoln Ave, Saugus, MA 01906",
        "city": "Saugus",
        "zip_code": "01906",
        "specialty": "Exotic Animals",
        "services": "Avian, Reptile, Small Mammal, Wildlife, Surgery, Dentistry",
        "is_emergency": False,
    },
    # ── South/SE MA ───────────────────────────────────────────
    {
        "clinic_name": "Fall River Animal Hospital",
        "phone": "(508) 672-6101",
        "address": "3239 N Main St, Fall River, MA 02720",
        "city": "Fall River",
        "zip_code": "02720",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostics",
        "is_emergency": False,
    },
    {
        "clinic_name": "Dartmouth Veterinary Hospital",
        "phone": "(508) 999-8100",
        "address": "311 State Rd, Dartmouth, MA 02747",
        "city": "Dartmouth",
        "zip_code": "02747",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Boarding",
        "is_emergency": False,
    },
    {
        "clinic_name": "Taunton Animal Hospital",
        "phone": "(508) 822-2221",
        "address": "1138 County St, Taunton, MA 02780",
        "city": "Taunton",
        "zip_code": "02780",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Diagnostics, Dental Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Easton Animal Hospital",
        "phone": "(508) 238-1777",
        "address": "565 Washington St, Easton, MA 02375",
        "city": "Easton",
        "zip_code": "02375",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Diagnostics, Laser Therapy, Boarding",
        "is_emergency": False,
    },
    # ── More MetroWest ────────────────────────────────────────
    {
        "clinic_name": "VCA Natick Animal Hospital",
        "phone": "(508) 653-4811",
        "address": "197 W Central St, Natick, MA 01760",
        "city": "Natick",
        "zip_code": "01760",
        "website": "https://vcahospitals.com/natick",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Diagnostic Imaging",
        "is_emergency": False,
    },
    {
        "clinic_name": "Hopkinton Animal Hospital",
        "phone": "(508) 435-4343",
        "address": "74 Main St, Hopkinton, MA 01748",
        "city": "Hopkinton",
        "zip_code": "01748",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Dentistry, Nutrition, Rehab",
        "is_emergency": False,
    },
    {
        "clinic_name": "Milford Animal Hospital",
        "phone": "(508) 473-3891",
        "address": "21 Congress St, Milford, MA 01757",
        "city": "Milford",
        "zip_code": "01757",
        "specialty": "General Practice",
        "services": "Wellness, Vaccinations, Surgery, Diagnostics, Dental Care",
        "is_emergency": False,
    },
    {
        "clinic_name": "Grafton Animal Hospital",
        "phone": "(508) 839-4400",
        "address": "9 Westboro Rd, Grafton, MA 01519",
        "city": "Grafton",
        "zip_code": "01519",
        "specialty": "General Practice",
        "services": "Wellness, Surgery, Dentistry, Microchipping, Senior Care",
        "is_emergency": False,
    },
]


async def seed():
    async with AsyncSessionLocal() as db:
        # Check if we already have records
        result = await db.execute(select(VetClinicRef).limit(1))
        if result.scalars().first():
            print("vet_clinic_refs already has data — skipping seed.")
            return

        now = datetime.utcnow()
        for c in MA_VET_CLINICS:
            clinic = VetClinicRef(
                clinic_name=c["clinic_name"],
                veterinarian_name=c.get("veterinarian_name"),
                phone=c.get("phone"),
                email=c.get("email"),
                address=c.get("address"),
                city=c.get("city"),
                state=c.get("state", "MA"),
                zip_code=c.get("zip_code"),
                website=c.get("website"),
                specialty=c.get("specialty"),
                services=c.get("services"),
                is_emergency=c.get("is_emergency", False),
                is_active=True,
                created_at=now,
                updated_at=now,
            )
            db.add(clinic)

        await db.commit()
        print(f"Seeded {len(MA_VET_CLINICS)} MA vet clinics.")


if __name__ == "__main__":
    asyncio.run(seed())
