"""
Common veterinary medications reference data.
Each entry includes drug details, indications, species, and common side effects.
"""

COMMON_MEDICATIONS: list[dict] = [
    # ── NSAIDs / Pain ──────────────────────────────────────────
    {
        "drug_name": "Carprofen (Rimadyl)",
        "drug_class": "NSAID",
        "species": ["dog"],
        "common_indications": "Osteoarthritis pain, post-surgical pain, inflammation",
        "typical_dose": "2.2 mg/kg twice daily or 4.4 mg/kg once daily",
        "route": "Oral / Injectable",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Liver enzyme elevation",
            "GI ulceration (rare)",
            "Kidney injury (rare)",
        ],
        "warnings": "Not for use in cats. Monitor liver and kidney values. Avoid with other NSAIDs or corticosteroids.",
    },
    {
        "drug_name": "Meloxicam (Metacam)",
        "drug_class": "NSAID",
        "species": ["dog", "cat"],
        "common_indications": "Osteoarthritis, pain management, inflammation",
        "typical_dose": "Dogs: 0.1 mg/kg daily; Cats: 0.05 mg/kg (short-term only in cats)",
        "route": "Oral suspension / Injectable",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Lethargy",
            "GI ulceration",
            "Renal toxicity (especially cats)",
        ],
        "warnings": "Long-term use in cats is controversial — monitor kidney function closely. Not for dehydrated patients.",
    },
    {
        "drug_name": "Galliprant (Grapiprant)",
        "drug_class": "NSAID (Piprant)",
        "species": ["dog"],
        "common_indications": "Osteoarthritis pain and inflammation",
        "typical_dose": "2 mg/kg once daily",
        "route": "Oral tablet",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Soft stool",
            "Decreased appetite",
            "Lethargy",
        ],
        "warnings": "Not for cats. May be gentler on GI than traditional NSAIDs. Avoid combining with other NSAIDs or corticosteroids.",
    },
    # ── Allergy / Itch ─────────────────────────────────────────
    {
        "drug_name": "Apoquel (Oclacitinib)",
        "drug_class": "Janus Kinase (JAK) inhibitor",
        "species": ["dog"],
        "common_indications": "Allergic dermatitis, atopic dermatitis, pruritus (itching)",
        "typical_dose": "0.4–0.6 mg/kg twice daily for 14 days, then once daily",
        "route": "Oral tablet",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Lethargy",
            "Increased susceptibility to infections",
            "Possible increased risk of neoplasia with long-term use",
        ],
        "warnings": "Not for dogs under 12 months. Not for dogs with serious infections or neoplasia. Not for cats.",
    },
    {
        "drug_name": "Cytopoint (Lokivetmab)",
        "drug_class": "Monoclonal antibody",
        "species": ["dog"],
        "common_indications": "Atopic dermatitis, allergic itching",
        "typical_dose": "1–2 mg/kg injection every 4–8 weeks",
        "route": "Subcutaneous injection",
        "common_side_effects": [
            "Injection site reactions (rare)",
            "Vomiting (uncommon)",
            "Lethargy (uncommon)",
        ],
        "warnings": "Administered by veterinarian. Very well tolerated. Not for cats.",
    },
    {
        "drug_name": "Diphenhydramine (Benadryl)",
        "drug_class": "Antihistamine",
        "species": ["dog", "cat"],
        "common_indications": "Mild allergic reactions, itching, motion sickness, mild sedation",
        "typical_dose": "Dogs: 1–2 mg/kg every 8–12 hours; Cats: 1–2 mg/kg every 8–12 hours",
        "route": "Oral / Injectable",
        "common_side_effects": [
            "Drowsiness / sedation",
            "Dry mouth",
            "Urinary retention",
            "GI upset",
        ],
        "warnings": "Use plain diphenhydramine only — avoid formulations with decongestants (pseudoephedrine) or xylitol.",
    },
    {
        "drug_name": "Cyclosporine (Atopica)",
        "drug_class": "Immunosuppressant",
        "species": ["dog", "cat"],
        "common_indications": "Atopic dermatitis, immune-mediated diseases, dry eye (topical)",
        "typical_dose": "Dogs: 5 mg/kg daily; Cats: 7 mg/kg daily",
        "route": "Oral capsule/liquid",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Gingival hyperplasia (dogs)",
            "Increased susceptibility to infections",
            "Papillomatosis (wart-like growths)",
        ],
        "warnings": "Give on empty stomach. Avoid live vaccines during treatment. Monitor for infections.",
    },
    # ── Antibiotics ────────────────────────────────────────────
    {
        "drug_name": "Amoxicillin",
        "drug_class": "Penicillin antibiotic",
        "species": ["dog", "cat"],
        "common_indications": "Bacterial infections (skin, urinary, respiratory)",
        "typical_dose": "10–25 mg/kg every 8–12 hours",
        "route": "Oral tablet / liquid",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Allergic reaction (rare)",
        ],
        "warnings": "Not effective against beta-lactamase producing bacteria. Complete the full course.",
    },
    {
        "drug_name": "Amoxicillin/Clavulanate (Clavamox)",
        "drug_class": "Penicillin + beta-lactamase inhibitor",
        "species": ["dog", "cat"],
        "common_indications": "Skin infections, urinary tract infections, respiratory infections, bite wounds",
        "typical_dose": "12.5–25 mg/kg every 8–12 hours",
        "route": "Oral tablet / drops",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Allergic reaction (rare)",
        ],
        "warnings": "Give with food to reduce GI upset. Refrigerate liquid form. Complete the full course.",
    },
    {
        "drug_name": "Doxycycline",
        "drug_class": "Tetracycline antibiotic",
        "species": ["dog", "cat"],
        "common_indications": "Tick-borne diseases (Lyme, Ehrlichia, Anaplasma), respiratory infections, Bartonella, Mycoplasma",
        "typical_dose": "5–10 mg/kg every 12–24 hours",
        "route": "Oral tablet / capsule",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Esophageal stricture (cats — give with food/water)",
            "Photosensitivity",
            "Teeth discoloration in puppies/kittens",
        ],
        "warnings": "Always follow with food or water (especially cats) to prevent esophageal damage. Avoid in very young animals.",
    },
    {
        "drug_name": "Metronidazole (Flagyl)",
        "drug_class": "Nitroimidazole antibiotic / antiprotozoal",
        "species": ["dog", "cat"],
        "common_indications": "Giardia, inflammatory bowel disease, anaerobic bacterial infections, diarrhea",
        "typical_dose": "10–15 mg/kg every 12 hours",
        "route": "Oral tablet / liquid",
        "common_side_effects": [
            "Nausea / vomiting",
            "Decreased appetite",
            "Drooling (bitter taste)",
            "Neurotoxicity at high doses (ataxia, seizures)",
        ],
        "warnings": "Do not exceed recommended doses — neurotoxicity risk. Avoid in pregnant animals. Very bitter taste.",
    },
    {
        "drug_name": "Enrofloxacin (Baytril)",
        "drug_class": "Fluoroquinolone antibiotic",
        "species": ["dog", "cat"],
        "common_indications": "Urinary tract infections, skin infections, respiratory infections, prostatitis",
        "typical_dose": "Dogs: 5–20 mg/kg daily; Cats: 5 mg/kg daily",
        "route": "Oral tablet / Injectable",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Cartilage damage in growing animals",
            "Retinal toxicity in cats (blindness at high doses)",
        ],
        "warnings": "Do NOT exceed 5 mg/kg/day in cats — risk of irreversible blindness. Avoid in growing puppies/kittens.",
    },
    {
        "drug_name": "Cephalexin (Keflex)",
        "drug_class": "Cephalosporin antibiotic",
        "species": ["dog", "cat"],
        "common_indications": "Skin infections (pyoderma), urinary tract infections, soft tissue infections",
        "typical_dose": "22–30 mg/kg every 8–12 hours",
        "route": "Oral capsule / tablet",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Drooling",
        ],
        "warnings": "Complete the full course. Cross-reactivity possible in penicillin-allergic patients (rare).",
    },
    # ── Corticosteroids ────────────────────────────────────────
    {
        "drug_name": "Prednisone / Prednisolone",
        "drug_class": "Corticosteroid",
        "species": ["dog", "cat"],
        "common_indications": "Allergies, inflammation, immune-mediated disease, asthma (cats), Addison's disease",
        "typical_dose": "Anti-inflammatory: 0.5–1 mg/kg/day; Immunosuppressive: 2–4 mg/kg/day; taper gradually",
        "route": "Oral tablet / liquid / Injectable",
        "common_side_effects": [
            "Increased thirst (polydipsia)",
            "Increased urination (polyuria)",
            "Increased appetite (polyphagia)",
            "Weight gain",
            "Panting",
            "GI ulceration",
            "Muscle wasting (chronic use)",
            "Iatrogenic Cushing's syndrome (chronic use)",
            "Immunosuppression",
        ],
        "warnings": "Use prednisolone (not prednisone) in cats — cats cannot convert prednisone well. Taper gradually; do not stop abruptly. Avoid with NSAIDs.",
    },
    # ── GI / Anti-nausea ───────────────────────────────────────
    {
        "drug_name": "Cerenia (Maropitant)",
        "drug_class": "NK1 receptor antagonist",
        "species": ["dog", "cat"],
        "common_indications": "Vomiting, motion sickness, nausea",
        "typical_dose": "Dogs: 2 mg/kg daily (oral) or 1 mg/kg (injectable); Cats: 1 mg/kg daily (injectable)",
        "route": "Oral tablet / Injectable",
        "common_side_effects": [
            "Drooling (if given orally — bitter)",
            "Pain at injection site",
            "Lethargy",
            "Decreased appetite",
        ],
        "warnings": "Hide tablet in food to avoid drooling. Injectable can sting — refrigerate before giving. Very effective anti-emetic.",
    },
    {
        "drug_name": "Omeprazole (Prilosec)",
        "drug_class": "Proton pump inhibitor",
        "species": ["dog", "cat"],
        "common_indications": "Gastric ulcers, acid reflux, esophagitis, NSAID-induced GI protection",
        "typical_dose": "1 mg/kg every 12–24 hours",
        "route": "Oral capsule / tablet",
        "common_side_effects": [
            "Diarrhea",
            "Nausea",
            "Flatulence",
            "Rebound acid hypersecretion on discontinuation",
        ],
        "warnings": "Give on empty stomach 30 min before food for best effect. Taper when discontinuing after long-term use.",
    },
    {
        "drug_name": "Sucralfate (Carafate)",
        "drug_class": "GI protectant",
        "species": ["dog", "cat"],
        "common_indications": "Gastric/esophageal ulcers, erosive gastritis",
        "typical_dose": "Dogs: 0.5–1 g every 8 hours; Cats: 0.25–0.5 g every 8–12 hours",
        "route": "Oral tablet / suspension",
        "common_side_effects": [
            "Constipation",
            "Aluminum toxicity (rare, renal-impaired patients)",
        ],
        "warnings": "Give on empty stomach. Separate from other medications by 2 hours — sucralfate binds other drugs and reduces absorption.",
    },
    # ── Heart ──────────────────────────────────────────────────
    {
        "drug_name": "Pimobendan (Vetmedin)",
        "drug_class": "Inodilator (positive inotrope + vasodilator)",
        "species": ["dog"],
        "common_indications": "Congestive heart failure (CHF), dilated cardiomyopathy (DCM), mitral valve disease",
        "typical_dose": "0.25–0.3 mg/kg every 12 hours",
        "route": "Oral chewable tablet",
        "common_side_effects": [
            "Decreased appetite",
            "Diarrhea",
            "Lethargy",
            "Arrhythmias (rare)",
        ],
        "warnings": "Give on empty stomach (1 hour before food). Do not use in hypertrophic cardiomyopathy or aortic stenosis.",
    },
    {
        "drug_name": "Enalapril (Enacard)",
        "drug_class": "ACE inhibitor",
        "species": ["dog", "cat"],
        "common_indications": "Heart failure, hypertension, protein-losing nephropathy",
        "typical_dose": "0.5 mg/kg every 12–24 hours",
        "route": "Oral tablet",
        "common_side_effects": [
            "Decreased appetite",
            "Vomiting",
            "Diarrhea",
            "Hypotension",
            "Elevated kidney values",
            "Hyperkalemia",
        ],
        "warnings": "Monitor kidney values and electrolytes. Reduce dose in renal-impaired patients. Avoid in pregnancy.",
    },
    {
        "drug_name": "Furosemide (Lasix)",
        "drug_class": "Loop diuretic",
        "species": ["dog", "cat"],
        "common_indications": "Congestive heart failure (pulmonary edema), ascites, edema",
        "typical_dose": "1–4 mg/kg every 8–12 hours (adjust to effect)",
        "route": "Oral tablet / Injectable",
        "common_side_effects": [
            "Increased urination",
            "Increased thirst",
            "Dehydration",
            "Electrolyte imbalances (hypokalemia)",
            "Ototoxicity at very high IV doses",
        ],
        "warnings": "Monitor hydration and electrolytes closely. Keep fresh water available at all times.",
    },
    # ── Seizures / Neuro ───────────────────────────────────────
    {
        "drug_name": "Phenobarbital",
        "drug_class": "Barbiturate anticonvulsant",
        "species": ["dog", "cat"],
        "common_indications": "Epilepsy, seizure management",
        "typical_dose": "2–5 mg/kg every 12 hours (adjust based on serum levels)",
        "route": "Oral tablet / liquid / Injectable",
        "common_side_effects": [
            "Sedation / ataxia (initially)",
            "Increased thirst",
            "Increased urination",
            "Increased appetite / weight gain",
            "Liver enzyme elevation / hepatotoxicity",
        ],
        "warnings": "Monitor serum phenobarbital levels and liver values regularly. Do NOT stop abruptly — taper to avoid rebound seizures. DEA controlled substance.",
    },
    {
        "drug_name": "Zonisamide (Zonegran)",
        "drug_class": "Sulfonamide anticonvulsant",
        "species": ["dog", "cat"],
        "common_indications": "Epilepsy (add-on or alternative to phenobarbital)",
        "typical_dose": "Dogs: 5–10 mg/kg every 12 hours; Cats: 5–10 mg/kg every 24 hours",
        "route": "Oral capsule",
        "common_side_effects": [
            "Sedation",
            "Ataxia",
            "Decreased appetite",
            "Vomiting",
            "Hepatotoxicity (rare)",
        ],
        "warnings": "May be better tolerated than phenobarbital for liver. Sulfonamide — use cautiously if prior sulfa allergy.",
    },
    {
        "drug_name": "Gabapentin",
        "drug_class": "Anticonvulsant / Analgesic",
        "species": ["dog", "cat"],
        "common_indications": "Neuropathic pain, chronic pain, anxiety, pre-visit sedation (cats), adjunct seizure control",
        "typical_dose": "Dogs: 5–10 mg/kg every 8–12 hours; Cats: 5–10 mg/kg every 8–12 hours (or 50–100 mg pre-visit)",
        "route": "Oral capsule / tablet / liquid",
        "common_side_effects": [
            "Sedation / drowsiness",
            "Ataxia / wobbliness",
            "GI upset",
        ],
        "warnings": "Avoid liquid formulations containing xylitol (toxic to dogs). Start low and increase gradually.",
    },
    # ── Anxiety / Behavior ─────────────────────────────────────
    {
        "drug_name": "Trazodone",
        "drug_class": "Serotonin antagonist/reuptake inhibitor (SARI)",
        "species": ["dog", "cat"],
        "common_indications": "Situational anxiety, storm/noise phobia, post-surgical confinement, travel anxiety",
        "typical_dose": "Dogs: 3–7 mg/kg every 8–24 hours; Cats: 50–100 mg per cat",
        "route": "Oral tablet",
        "common_side_effects": [
            "Sedation",
            "GI upset",
            "Ataxia",
            "Agitation (paradoxical, rare)",
            "Priapism (rare)",
        ],
        "warnings": "Avoid combining with MAOIs or other serotonergic drugs (serotonin syndrome risk). Can cause paradoxical excitement in some animals.",
    },
    {
        "drug_name": "Fluoxetine (Prozac / Reconcile)",
        "drug_class": "Selective serotonin reuptake inhibitor (SSRI)",
        "species": ["dog", "cat"],
        "common_indications": "Separation anxiety, generalized anxiety, compulsive behaviors, urine marking (cats)",
        "typical_dose": "Dogs: 1–2 mg/kg daily; Cats: 0.5–1 mg/kg daily",
        "route": "Oral tablet / capsule",
        "common_side_effects": [
            "Decreased appetite",
            "Lethargy",
            "GI upset",
            "Agitation/anxiety (initial days)",
            "Urinary retention (rare)",
        ],
        "warnings": "Takes 4–6 weeks for full behavioral effect. Do not combine with MAOIs or tramadol. Taper when discontinuing.",
    },
    # ── Flea/Tick / Heartworm Prevention ───────────────────────
    {
        "drug_name": "Simparica Trio (Sarolaner/Moxidectin/Pyrantel)",
        "drug_class": "Isoxazoline combination",
        "species": ["dog"],
        "common_indications": "Flea/tick prevention, heartworm prevention, intestinal parasite treatment",
        "typical_dose": "Weight-based chewable tablet once monthly",
        "route": "Oral chewable",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Lethargy",
            "Seizures (rare — isoxazoline class warning)",
        ],
        "warnings": "Use with caution in dogs with a history of seizures. Isoxazoline class has FDA seizure advisory. Not for cats.",
    },
    {
        "drug_name": "Bravecto (Fluralaner)",
        "drug_class": "Isoxazoline",
        "species": ["dog", "cat"],
        "common_indications": "Flea and tick prevention (12-week dosing for dogs)",
        "typical_dose": "Weight-based chewable (dogs) or topical (cats) every 12 weeks",
        "route": "Oral chewable (dogs) / Topical (cats)",
        "common_side_effects": [
            "Vomiting",
            "Diarrhea",
            "Decreased appetite",
            "Lethargy",
            "Seizures (rare — isoxazoline class warning)",
        ],
        "warnings": "Isoxazoline class — use cautiously in seizure-prone animals. FDA advisory for neurologic events.",
    },
    {
        "drug_name": "Heartgard Plus (Ivermectin/Pyrantel)",
        "drug_class": "Macrocyclic lactone + anthelmintic",
        "species": ["dog"],
        "common_indications": "Heartworm prevention, treatment of roundworms and hookworms",
        "typical_dose": "Weight-based chewable once monthly",
        "route": "Oral chewable",
        "common_side_effects": [
            "Vomiting (rare)",
            "Diarrhea (rare)",
            "Lethargy (rare)",
        ],
        "warnings": "Test for heartworm before starting. MDR1 gene mutation dogs (Collies, Shelties, Aussies) — safe at preventive dose but higher doses dangerous.",
    },
    # ── Thyroid ────────────────────────────────────────────────
    {
        "drug_name": "Methimazole (Tapazole / Felimazole)",
        "drug_class": "Anti-thyroid",
        "species": ["cat"],
        "common_indications": "Hyperthyroidism",
        "typical_dose": "1.25–5 mg every 12 hours (start low, adjust to T4 levels)",
        "route": "Oral tablet / transdermal gel",
        "common_side_effects": [
            "Vomiting",
            "Decreased appetite",
            "Lethargy",
            "Facial excoriation (itching/scratching face)",
            "Blood dyscrasias (rare — low WBC/platelets)",
            "Hepatotoxicity (rare)",
        ],
        "warnings": "Monitor T4, CBC, liver and kidney values every 2–4 weeks initially, then every 3–6 months. Masking renal disease is common.",
    },
    {
        "drug_name": "Levothyroxine (Soloxine / Thyro-Tabs)",
        "drug_class": "Thyroid hormone replacement",
        "species": ["dog"],
        "common_indications": "Hypothyroidism",
        "typical_dose": "0.02 mg/kg every 12 hours (adjust to T4 levels)",
        "route": "Oral tablet / chewable",
        "common_side_effects": [
            "Restlessness (if overdosed)",
            "Increased thirst/urination (if overdosed)",
            "Tachycardia (if overdosed)",
            "Weight loss (if overdosed)",
        ],
        "warnings": "Side effects are usually signs of overdose — adjust dose down. Monitor T4 levels 4–6 hours post-pill. Give on empty stomach ideally.",
    },
    # ── Miscellaneous ──────────────────────────────────────────
    {
        "drug_name": "Tramadol",
        "drug_class": "Opioid analgesic",
        "species": ["dog", "cat"],
        "common_indications": "Moderate pain management, adjunct pain therapy",
        "typical_dose": "Dogs: 2–5 mg/kg every 8–12 hours; Cats: 1–2 mg/kg every 12 hours",
        "route": "Oral tablet",
        "common_side_effects": [
            "Sedation",
            "Constipation",
            "Nausea",
            "Dysphoria",
            "Decreased appetite",
        ],
        "warnings": "Efficacy in dogs is debated (poor mu-opioid activity). More effective in cats. DEA controlled substance. Avoid with SSRIs/MAOIs (serotonin syndrome).",
    },
    {
        "drug_name": "Maropitant + Famotidine + Metoclopramide (GI Cocktail)",
        "drug_class": "Combination antiemetic therapy",
        "species": ["dog", "cat"],
        "common_indications": "Severe vomiting, pancreatitis-associated nausea, post-anesthetic nausea",
        "typical_dose": "Each drug dosed individually per body weight",
        "route": "Oral / Injectable (per drug)",
        "common_side_effects": [
            "Sedation",
            "Restlessness (metoclopramide)",
            "Hypotension",
            "Extrapyramidal signs (metoclopramide — rare)",
        ],
        "warnings": "Metoclopramide contraindicated in GI obstruction and seizure patients. Typically used in-hospital.",
    },
    {
        "drug_name": "Adequan (Polysulfated Glycosaminoglycan)",
        "drug_class": "Disease-modifying osteoarthritis drug (DMOAD)",
        "species": ["dog"],
        "common_indications": "Osteoarthritis, joint disease, cartilage protection",
        "typical_dose": "5 mg/kg IM twice weekly for 4 weeks, then monthly",
        "route": "Intramuscular injection",
        "common_side_effects": [
            "Pain at injection site",
            "Diarrhea (rare)",
            "Bleeding abnormalities (rare — anticoagulant-like effect)",
        ],
        "warnings": "Avoid in animals with known bleeding disorders. Injectable only — veterinary administration typically.",
    },
]
