"""add_labs_table

Revision ID: 29b5351e258d
Revises: 8a119e0ab97b
Create Date: 2026-02-17 11:59:11.871260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b5351e258d'
down_revision: Union[str, None] = '8a119e0ab97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('lab_type', sa.String(length=50), nullable=False),
    sa.Column('lab_date', sa.DateTime(), nullable=True),
    sa.Column('veterinarian', sa.String(length=200), nullable=True),
    sa.Column('clinic', sa.String(length=200), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_id'), 'labs', ['id'], unique=False)
    op.create_index(op.f('ix_labs_pet_id'), 'labs', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labs_pet_id'), table_name='labs')
    op.drop_index(op.f('ix_labs_id'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
