"""add_insurance_table

Revision ID: 49c4daa69890
Revises: 29b5351e258d
Create Date: 2026-02-17 12:37:08.643351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c4daa69890'
down_revision: Union[str, None] = '29b5351e258d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('has_insurance', sa.Boolean(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('group_number', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('coverage_type', sa.String(length=50), nullable=True),
    sa.Column('deductible', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('co_pay_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('annual_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurances_id'), 'insurances', ['id'], unique=False)
    op.create_index(op.f('ix_insurances_pet_id'), 'insurances', ['pet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurances_pet_id'), table_name='insurances')
    op.drop_index(op.f('ix_insurances_id'), table_name='insurances')
    op.drop_table('insurances')
    # ### end Alembic commands ###
