"""add_appointments_vitals_vetproviders_activitynotes

Revision ID: df3517c516dd
Revises: ed209f1fec70
Create Date: 2026-02-17 15:14:23.597424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3517c516dd'
down_revision: Union[str, None] = 'ed209f1fec70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vet_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sa.String(length=300), nullable=False),
    sa.Column('veterinarian_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vet_providers_id'), 'vet_providers', ['id'], unique=False)
    op.create_index(op.f('ix_vet_providers_owner_id'), 'vet_providers', ['owner_id'], unique=False)
    op.create_table('activity_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('note_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_notes_id'), 'activity_notes', ['id'], unique=False)
    op.create_index(op.f('ix_activity_notes_pet_id'), 'activity_notes', ['pet_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('clinic', sa.String(length=200), nullable=True),
    sa.Column('veterinarian', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_pet_id'), 'appointments', ['pet_id'], unique=False)
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('recorded_date', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitals_id'), 'vitals', ['id'], unique=False)
    op.create_index(op.f('ix_vitals_pet_id'), 'vitals', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitals_pet_id'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_index(op.f('ix_appointments_pet_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_activity_notes_pet_id'), table_name='activity_notes')
    op.drop_index(op.f('ix_activity_notes_id'), table_name='activity_notes')
    op.drop_table('activity_notes')
    op.drop_index(op.f('ix_vet_providers_owner_id'), table_name='vet_providers')
    op.drop_index(op.f('ix_vet_providers_id'), table_name='vet_providers')
    op.drop_table('vet_providers')
    # ### end Alembic commands ###
