"""add_common_medication_refs_table

Revision ID: ed209f1fec70
Revises: 49c4daa69890
Create Date: 2026-02-17 13:32:29.355697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed209f1fec70'
down_revision: Union[str, None] = '49c4daa69890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_medication_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('drug_class', sa.String(length=100), nullable=False),
    sa.Column('species', sa.JSON(), nullable=False),
    sa.Column('common_indications', sa.String(length=500), nullable=False),
    sa.Column('typical_dose', sa.String(length=500), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('common_side_effects', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_medication_refs_drug_name'), 'common_medication_refs', ['drug_name'], unique=True)
    op.create_index(op.f('ix_common_medication_refs_id'), 'common_medication_refs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_medication_refs_id'), table_name='common_medication_refs')
    op.drop_index(op.f('ix_common_medication_refs_drug_name'), table_name='common_medication_refs')
    op.drop_table('common_medication_refs')
    # ### end Alembic commands ###
